# Generated by Django 6.0 on 2026-01-19 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='দোকানের নাম')),
                ('slug', models.SlugField(help_text='URL friendly name', max_length=100, unique=True)),
                ('owner_name', models.CharField(max_length=200, verbose_name='মালিকের নাম')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('phone', models.CharField(max_length=20, verbose_name='ফোন')),
                ('address', models.TextField(blank=True, verbose_name='ঠিকানা')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'দোকান',
                'verbose_name_plural': 'দোকান সমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'ফ্রি'), ('basic', 'বেসিক'), ('premium', 'প্রিমিয়াম')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_products', models.IntegerField(default=50, help_text='সর্বোচ্চ পণ্য সংখ্যা')),
                ('max_users', models.IntegerField(default=1, help_text='সর্বোচ্চ ইউজার সংখ্যা')),
                ('max_monthly_sales', models.IntegerField(default=100, help_text='মাসিক সর্বোচ্চ বিক্রি')),
                ('has_reports', models.BooleanField(default=True)),
                ('has_barcode', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_multiple_locations', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'সাবস্ক্রিপশন প্ল্যান',
                'verbose_name_plural': 'সাবস্ক্রিপশন প্ল্যান',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'মাসিক'), ('yearly', 'বার্ষিক')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'সক্রিয়'), ('expired', 'মেয়াদ শেষ'), ('cancelled', 'বাতিল'), ('pending', 'পেন্ডিং')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.subscriptionplan')),
            ],
            options={
                'verbose_name': 'সাবস্ক্রিপশন',
                'verbose_name_plural': 'সাবস্ক্রিপশন',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.subscriptionplan'),
        ),
    ]
