# Generated by Django 6.0 on 2026-01-19 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='বর্তমান পরিমাণ')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='পুনঃঅর্ডার লেভেল')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product', verbose_name='পণ্য')),
            ],
            options={
                'verbose_name': 'স্টক',
                'verbose_name_plural': 'স্টক সমূহ',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='বার্তা')),
                ('is_read', models.BooleanField(default=False, verbose_name='পড়া হয়েছে')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.stock', verbose_name='স্টক')),
            ],
            options={
                'verbose_name': 'স্টক অ্যালার্ট',
                'verbose_name_plural': 'স্টক অ্যালার্ট সমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'স্টক ইন'), ('out', 'স্টক আউট'), ('adjustment', 'সমন্বয়'), ('return', 'রিটার্ন')], max_length=20, verbose_name='মুভমেন্ট টাইপ')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='পরিমাণ')),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='আগের পরিমাণ')),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='নতুন পরিমাণ')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='রেফারেন্স')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='পণ্য')),
            ],
            options={
                'verbose_name': 'স্টক মুভমেন্ট',
                'verbose_name_plural': 'স্টক মুভমেন্ট সমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
