# Generated by Django 6.0 on 2026-01-19 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='তারিখ')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='প্রারম্ভিক ব্যালেন্স')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='মোট আয়')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='মোট ব্যয়')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='সমাপনী ব্যালেন্স')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('is_closed', models.BooleanField(default=False, verbose_name='বন্ধ')),
            ],
            options={
                'verbose_name': 'দৈনিক ক্যাশ ফ্লো',
                'verbose_name_plural': 'দৈনিক ক্যাশ ফ্লো সমূহ',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'দোকান ভাড়া'), ('salary', 'বেতন'), ('electricity', 'বিদ্যুৎ বিল'), ('water', 'পানি বিল'), ('internet', 'ইন্টারনেট বিল'), ('transport', 'পরিবহন'), ('packaging', 'প্যাকেজিং'), ('maintenance', 'মেরামত'), ('marketing', 'মার্কেটিং'), ('other', 'অন্যান্য')], max_length=30, verbose_name='ক্যাটাগরি')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='টাকার পরিমাণ')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='তারিখ')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='expenses/', verbose_name='রিসিট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'খরচ',
                'verbose_name_plural': 'খরচ সমূহ',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'আয়'), ('expense', 'ব্যয়')], max_length=20, verbose_name='লেনদেনের ধরণ')),
                ('category', models.CharField(choices=[('sale', 'বিক্রয়'), ('purchase', 'ক্রয়'), ('payment_received', 'পেমেন্ট গ্রহণ'), ('payment_made', 'পেমেন্ট প্রদান'), ('salary', 'বেতন'), ('rent', 'ভাড়া'), ('utility', 'ইউটিলিটি বিল'), ('transport', 'পরিবহন'), ('other', 'অন্যান্য')], max_length=30, verbose_name='ক্যাটাগরি')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='টাকার পরিমাণ')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='রেফারেন্স')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='তারিখ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'লেনদেন',
                'verbose_name_plural': 'লেনদেন সমূহ',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
