# Generated by Django 6.0 on 2026-01-19 05:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='গ্রাহকের নাম')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='ফোন নম্বর')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল')),
                ('address', models.TextField(blank=True, verbose_name='ঠিকানা')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='প্রতিষ্ঠান')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'গ্রাহক',
                'verbose_name_plural': 'গ্রাহকগণ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='ইনভয়েস নম্বর')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='উপমোট')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ছাড়')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ছাড় %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ট্যাক্স')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='সর্বমোট')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='প্রদত্ত টাকা')),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='বাকি টাকা')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ফেরত')),
                ('payment_status', models.CharField(choices=[('paid', 'পরিশোধিত'), ('partial', 'আংশিক'), ('unpaid', 'অপরিশোধিত')], default='unpaid', max_length=20, verbose_name='পেমেন্ট স্ট্যাটাস')),
                ('payment_method', models.CharField(choices=[('cash', 'নগদ'), ('card', 'কার্ড'), ('mobile', 'মোবাইল ব্যাংকিং'), ('bank', 'ব্যাংক ট্রান্সফার'), ('credit', 'বাকি')], default='cash', max_length=20, verbose_name='পেমেন্ট মাধ্যম')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='বিক্রয়ের তারিখ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='বিক্রেতা')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.customer', verbose_name='গ্রাহক')),
            ],
            options={
                'verbose_name': 'বিক্রয়',
                'verbose_name_plural': 'বিক্রয় সমূহ',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='টাকার পরিমাণ')),
                ('payment_method', models.CharField(choices=[('cash', 'নগদ'), ('card', 'কার্ড'), ('mobile', 'মোবাইল ব্যাংকিং'), ('bank', 'ব্যাংক ট্রান্সফার'), ('credit', 'বাকি')], max_length=20, verbose_name='পেমেন্ট মাধ্যম')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='রেফারেন্স')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='তারিখ')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='গ্রহণকারী')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='বিক্রয়')),
            ],
            options={
                'verbose_name': 'পেমেন্ট',
                'verbose_name_plural': 'পেমেন্ট সমূহ',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='পরিমাণ')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='একক মূল্য')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ছাড়')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='মোট')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='পণ্য')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='বিক্রয়')),
            ],
            options={
                'verbose_name': 'বিক্রয় আইটেম',
                'verbose_name_plural': 'বিক্রয় আইটেম সমূহ',
            },
        ),
    ]
