# Generated by Django 6.0 on 2026-01-19 05:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ক্যাটাগরির নাম')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ক্যাটাগরি',
                'verbose_name_plural': 'ক্যাটাগরিসমূহ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GSMType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True, verbose_name='GSM মান')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='বিবরণ')),
            ],
            options={
                'verbose_name': 'GSM টাইপ',
                'verbose_name_plural': 'GSM টাইপসমূহ',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='PaperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='সাইজের নাম')),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='প্রস্থ (মিমি)')),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='দৈর্ঘ্য (মিমি)')),
            ],
            options={
                'verbose_name': 'কাগজের সাইজ',
                'verbose_name_plural': 'কাগজের সাইজসমূহ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='একক')),
                ('short_name', models.CharField(max_length=10, verbose_name='সংক্ষিপ্ত নাম')),
            ],
            options={
                'verbose_name': 'একক',
                'verbose_name_plural': 'একক সমূহ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='পণ্যের নাম')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU কোড')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='বারকোড')),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ক্রয় মূল্য (৳)')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='বিক্রয় মূল্য (৳)')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='ছবি')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='ক্যাটাগরি')),
                ('gsm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.gsmtype', verbose_name='GSM')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.papersize', verbose_name='সাইজ')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.unit', verbose_name='একক')),
            ],
            options={
                'verbose_name': 'পণ্য',
                'verbose_name_plural': 'পণ্যসমূহ',
                'ordering': ['name'],
            },
        ),
    ]
